### ISSUE TITLE
[非紧急]关于 Magisk 模块的疑问

### ISSUE THREAD

**Issue by naranyinyun** [chenzyyzd/CuprumTurbo-Scheduler#3]
尊敬的 Chenzyyzd 您好，在您更新 Magisk 示例模块后，我有一些疑问:  
1. 如何实现分应用配置
2. 如果不 cd 到 /data/adb/modules/ct_module 则无法在终端中使用 CuDaemon  
3. 使用 CuDaemon 切换模式后没有反馈在 scheduler.log 上  

以上，非常抱歉打扰到您的日常生活，感谢您的解答

**Comment by chenzyyzd** [comment]
1.CuprumTurbo Scheduler原本的分应用配置是通过CuToolbox APP来实现的，如果想要在native层做到分应用配置的话可以尝试写一个附加程序来实现按应用自动修改cur_mode.txt。
2.CuDaemon并没有限制运行的目录，请检查是否给予了足够的权限(ROOT & chmod 0777)和终端命令是否正确(CuDaemon -R 【配置文件路径】【调度模式文件(cur_mode.txt)路径】【调度日志文件生成路径】)，另外CuDaemon是一个守护进程，成功启动之后就不会再占用终端。
3.切换模式请使用修改cur_mode.txt的方法实现，如果调度日志没有记录到模式被成功修改的话请检查CuDaemon进程是否被终止。

**Comment by naranyinyun** [comment]
> 1.CuprumTurbo Scheduler原本的分应用配置是通过CuToolbox APP来实现的，如果想要在native层做到分应用配置的话可以尝试写一个附加程序来实现按应用自动修改cur_mode.txt。 2.CuDaemon并没有限制运行的目录，请检查是否给予了足够的权限(ROOT & chmod 0777)和终端命令是否正确(CuDaemon -R 【配置文件路径】【调度模式文件(cur_mode.txt)路径】【调度日志文件生成路径】)，另外CuDaemon是一个守护进程，成功启动之后就不会再占用终端。 3.切换模式请使用修改cur_mode.txt的方法实现，如果调度日志没有记录到模式被成功修改的话请检查CuDaemon进程是否被终止。

好的,感谢您的回复
