### ISSUE TITLE
关于支持GPU调频

### ISSUE THREAD

**Issue by XiaHuaBeiChiDiaoLe** [chenzyyzd/CuprumTurbo-Scheduler#4]
尊敬的 Chenzyyzd 你好，我在修改配置文件时发现没有单独针对GPU的调频参数，我想进一步省电和最佳能耗比，请问应该如何获取支持，感谢解答

**Comment by chenzyyzd** [comment]
GPU调频在不同平台上的效果差异太大且Soc厂商并没有提供统一的接口，难以像CPU一样做出多个平台通用的调度程序，所以CuprumTurbo在短期内没有加入GPU频率调整功能的计划。你可以试着额外写脚本或者程序进行GPU频率的调整。
