### ISSUE TITLE
MediaTek GPU 调频器工作异常

### ISSUE THREAD

**Issue by naranyinyun** [chenzyyzd/CuprumTurbo-Scheduler#6]
在 Redmi Note 8 Pro（AOSP Android 13） 上，GPU 调频器工作异常，具体如下：
1. 使用默认的配置文件，GPU 频率会锁定在270Mhz(最低频率)
2. 更改配置文件后，GPU 频率无变化(gpu_opp_freq 中无 GPU 频率相关信息)
3. Magisk 模块不工作(还没详细测试)

Cutoolbox: 3.7.1_alpha
配置文件(部分)：
```
# 更改前
  "MtkGpuGovernor": {
    "enable": true,
    "slowSampleTime": 40,
    "fastSampleTime": 20,
    "powersave": {
      "maxFreq": 600,
      "perfMargin": 10,
      "upRateLatency": 100
    },
    "balance": {
      "maxFreq": 700,
      "perfMargin": 20,
      "upRateLatency": 80
    },
    "performance": {
      "maxFreq": 800,
      "perfMargin": 25,
      "upRateLatency": 60
    },
    "fast": {
      "maxFreq": 900,
      "perfMargin": 30,
      "upRateLatency": 40
    }
  }
}
```
```
# 更改后，其他部分均未改动
  "MtkGpuGovernor": {
    "enable": true,
    "slowSampleTime": 40,
    "fastSampleTime": 20,
    "powersave": {
      "maxFreq": 370,
      "perfMargin": 10,
      "upRateLatency": 100
    },
    "balance": {
      "maxFreq": 700,
      "perfMargin": 20,
      "upRateLatency": 80
    },
    "performance": {
      "maxFreq": 800,
      "perfMargin": 25,
      "upRateLatency": 60
    },
    "fast": {
      "maxFreq": 900,
      "perfMargin": 30,
      "upRateLatency": 40
    }
  }
}
```

**Comment by chenzyyzd** [comment]
在天玑1000+ Android12L上测试一切正常。
可能是第三方内核的改动导致原有的接口丢失或数据异常。
请检查内核是否存在`/sys/kernel/ged/hal/gpu_utilization`或者`/sys/kernel/debug/ged/hal/gpu_utilization`节点以及节点提供的数据`%d %d %d`(例如2 0 98)是否正确（在GPU有负载时第一个和第三个数值应该存在跳变)。
另外附上调度log也可帮助开发者定位你提到的问题。

**Comment by naranyinyun** [comment]
> 

/sys/kernel/ged/hal/gpu_utilization 存在且负载发生变化时值也会变化
  (垃圾类原生截不了长屏

**Comment by naranyinyun** [comment]
![Screenshot_20230211-093400_CuToolbox](https://user-images.githubusercontent.com/91950505/218231758-1a81aea9-ef86-4ca0-b11b-440153b4e707.png)
![Screenshot_20230211-093417_Spark Launcher](https://user-images.githubusercontent.com/91950505/218231763-d432709f-9e50-4650-8b42-e72f3da405a4.png)

**Comment by chenzyyzd** [comment]
日志上看是没什么问题，可以试试把mali dvfs打开看打游戏的时候GPU频率会不会变化

**Comment by naranyinyun** [comment]
> 日志上看是没什么问题，可以试试把mali dvfs打开看打游戏的时候GPU频率会不会变化

有的，貌似1200上也有点问题(不确定)

**Comment by chenzyyzd** [comment]
暂时无法定位问题所在，但是开启dvfs似乎并不会影响写入GPU频率，下个版本会有所改进
