### ISSUE TITLE
MediaTek GPU 调频器 均衡模式调整异常

### ISSUE THREAD

**Issue by XiaHuaBeiChiDiaoLe** [chenzyyzd/CuprumTurbo-Scheduler#7]
在 Redmi K40 Gaming（MIUI Android 13） 上，GPU 调频器均衡模式调整异常，具体如下：

使用默认的配置文件，均衡模式GPU 频率会锁定在654Mhz(最高频率)但是默认配置写为700mhz 在700mhz附近有695mhz，705mhz这两个档位但却锁到了654mhz

更改配置文件后，均衡模式 GPU 频率锁471mhz(即使是手动改回原配置的700mhz也会锁471mhz )

未使用第三方内核以及干扰性能的模块
给予负载的软件为3Dmark

**Comment by naranyinyun** [comment]
参见 #6

**Comment by chenzyyzd** [comment]
CT不会使用全部的GPU频率，因为联发科默认的GPU频率挡位太多了，CT可以使用的GPU频率挡位可以参考调度日志，下个版本会改进一下频率表的生成方式。

**Comment by XiaHuaBeiChiDiaoLe** [comment]
主要是MTK的GPU的能耗比在某一个点上 比如1100 1200 1300的Mail G77 MC9 的几个能耗点在 512 654 735 感谢解答 不过还是希望每100 200mhz的范围有三个可选项

**Comment by XiaHuaBeiChiDiaoLe** [comment]
再次感谢chenzyyzd的辛勤付出

**Comment by XiaHuaBeiChiDiaoLe** [comment]
主要是MTK的GPU的能耗比在某一个点上 比如1100 1200 1300的Mail G77 MC9 的几个能耗点在 532 654 735 感谢解答 再次感谢chenzyyzd的辛勤付出
